version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1-stretch
    working_directory: /go/src/github.com/syucream/hakagi
    steps:
      - checkout
      - run: make dep cmd

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
